### ISSUE TITLE
Images not being rendered

### ISSUE THREAD

**Issue by ezerssss** [Miagao-Valley/mv-site#20]
Images listed in the `projects.md` file are not being rendered in the site.

The images are already present in the `/src/assets/projects`, but it doesn't seem to get the images.

**Ideas:**
Maybe astro can't render images outside of the `public` folder? I saw in the source code that the images used before are located in `public/assets`.

**Comment by ezerssss** [comment]
Console error messages:
![image](https://github.com/user-attachments/assets/871a4827-1383-4365-84f2-758b8325fda6)

Hmmm, I might be right nga Astro can't find the images. 404 not found.

**Comment by jrolana** [comment]
Thank you for this! Fixed it using imports. Images inside the src folder should be imported first.
